# Generated by Django 4.2.2 on 2023-06-12 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("location_api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="location",
            old_name="langitude",
            new_name="latitude",
        ),
    ]
