# Generated by Django 4.2.2 on 2023-06-12 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("location_api", "0003_rename_adress_location_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="address",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="location",
            name="country",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="location",
            name="name",
            field=models.CharField(max_length=155, null=True),
        ),
        migrations.AlterField(
            model_name="location",
            name="region",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
